; generated by fsp2hsc from curated/relay/relay_02/relay-02.lts
; CAC08 S1 decomposition: TASK_relay_a TASK_relay_t1
; leaf relay_a = TASK_relay_a, 6 states: 0=STATE1 1=STATE6 2=STATE5 3=STATE2 4=STATE4 5=STATE3
; leaf relay_t0 = TASK_relay_t0, 4 states: 0=STATE1 1=STATE2 2=STATE3 3=STATE6
; leaf relay_t1 = TASK_relay_t1, 4 states: 0=STATE1 1=STATE2 2=STATE3 3=STATE4
; leaf mon = property PROPERTY_always_1_between_zeros, 2 states + error 2: 0=STATE1 1=STATE2
(leaf relay_a 0 6)
(leaf relay_t0 0 4)
(leaf relay_t1 0 4)
(leaf mon 0 3)
(shape (spine relay_a relay_t0 relay_t1 mon))
(init)
(event internal_t0_ (when (== relay_t0 0)) (do (:= relay_t0 1)))
(event internal_t1_ (when (== relay_t1 0)) (do (:= relay_t1 1)))
(event rend_a_t0_a_get_end_0_ (when (== relay_a 1) (== relay_t0 2)) (do (:= relay_a 0) (:= relay_t0 3)))
(event rend_a_t0_a_get_end_1_ (when (== relay_a 4) (== relay_t0 2)) (do (:= relay_a 3) (:= relay_t0 1)))
(event rend_a_t1_a_get_end_0_ (when (== relay_a 2) (== relay_t1 2)) (do (:= relay_a 0) (:= relay_t1 1)))
(event rend_a_t1_a_get_end_1_ (when (== relay_a 5) (== relay_t1 2)) (do (:= relay_a 3) (:= relay_t1 3)))
(event rend_t0_a_get_0_t0___1 (when (== relay_a 0) (== relay_t0 1)) (do (:= relay_a 1) (:= relay_t0 2)))
(event rend_t0_a_get_0_t0___2 (when (== relay_a 3) (== relay_t0 1)) (do (:= relay_a 4) (:= relay_t0 2)))
(event rend_t0_a_set_1___1 (when (== relay_a 0) (== relay_t0 3) (== mon 0)) (do (:= relay_a 3) (:= relay_t0 1) (:= mon 1)))
(event rend_t0_a_set_1___2 (when (== relay_a 3) (== relay_t0 3) (== mon 0)) (do (:= relay_t0 1) (:= mon 1)))
(event rend_t0_a_set_1___3 (when (== relay_a 0) (== relay_t0 3) (in mon 1 2)) (do (:= relay_a 3) (:= relay_t0 1)))
(event rend_t0_a_set_1___4 (when (== relay_a 3) (== relay_t0 3) (in mon 1 2)) (do (:= relay_t0 1)))
(event rend_t1_a_get_0_t1___1 (when (== relay_a 0) (== relay_t1 1)) (do (:= relay_a 2) (:= relay_t1 2)))
(event rend_t1_a_get_0_t1___2 (when (== relay_a 3) (== relay_t1 1)) (do (:= relay_a 5) (:= relay_t1 2)))
(event rend_t1_a_set_0___1 (when (== relay_a 3) (== relay_t1 3) (== mon 1)) (do (:= relay_a 0) (:= relay_t1 1) (:= mon 0)))
(event rend_t1_a_set_0___2 (when (== relay_a 0) (== relay_t1 3) (== mon 1)) (do (:= relay_t1 1) (:= mon 0)))
(event rend_t1_a_set_0___3 (when (== relay_a 3) (== relay_t1 3) (== mon 0)) (do (:= relay_a 0) (:= relay_t1 1) (:= mon 2)))
(event rend_t1_a_set_0___4 (when (== relay_a 0) (== relay_t1 3) (== mon 0)) (do (:= relay_t1 1) (:= mon 2)))
(event rend_t1_a_set_0___5 (when (== relay_a 3) (== relay_t1 3) (== mon 2)) (do (:= relay_a 0) (:= relay_t1 1)))
(event rend_t1_a_set_0___6 (when (== relay_a 0) (== relay_t1 3) (== mon 2)) (do (:= relay_t1 1)))
