/// \file fsp2hsc.cc
/// \brief Import a CAC08 FSP (LTSA `.lts`) subject into the `.hsc` surface.
///
/// T2M (`fsp::parse`), M2LTS (`fsp::ground` per process), M2M
/// (`fsp::to_surface`), then the model-only `.hsc` to `-o` and its driver
/// to `--driver`. `--summary` reports what grounding and composition saw.
/// Exit: 0 ok, 1 parse error, 2 I/O, 3 ground/transform error (a model the
/// mapping does not cover).

#include <fstream>
#include <iostream>
#include <sstream>
#include <string>

#include <CLI/CLI.hpp>

#include "hsc/fsp/ast.hh"
#include "hsc/fsp/to_surface.hh"

namespace {

std::string basename_of(const std::string& path) {
  const std::size_t p = path.find_last_of('/');
  return p == std::string::npos ? path : path.substr(p + 1);
}

}  // namespace

int main(int argc, char** argv) {
  CLI::App app{"Import a CAC08 FSP (.lts) subject into the .hsc surface"};
  std::string in, out, driver, s1;
  std::size_t map_limit = 200;
  bool summary = false, parse_only = false, pinned = false;
  app.add_option("input", in, "the .lts subject")->required();
  app.add_option("-o,--output", out, "write the model .hsc here "
                                     "(default: stdout)");
  app.add_option("--driver", driver,
                 "also write a driver .hsc referencing the model by name");
  app.add_option("--s1", s1,
                 "the companion .txt naming the paper's decomposition; "
                 "recorded in the model header");
  app.add_option("--map-limit", map_limit,
                 "suppress a leaf's state-name map beyond this many states")
      ->capture_default_str();
  app.add_flag("--pinned", pinned,
               "split write pieces per source ((== P s) guards) so the "
               "hotbit rewrite's pinning eligibility holds");
  app.add_flag("--summary", summary,
               "report processes, alphabets, and composition, then stop");
  app.add_flag("--parse-only", parse_only, "stop silently after the parse");
  try {
    app.parse(argc, argv);
  } catch (const CLI::ParseError& e) {
    return app.exit(e) == 0 ? 0 : 2;
  }

  std::ifstream f(in, std::ios::binary);
  if (!f) {
    std::cerr << "cannot open " << in << '\n';
    return 2;
  }
  std::ostringstream buf;
  buf << f.rdbuf();

  try {
    const hsc::fsp::model m = hsc::fsp::parse(buf.str());
    if (parse_only) return 0;

    std::vector<hsc::fsp::ground_lts> procs;
    procs.reserve(m.processes.size());
    for (const hsc::fsp::process& p : m.processes)
      procs.push_back(hsc::fsp::ground(m, p));

    hsc::fsp::translation t = hsc::fsp::to_surface(procs, map_limit, pinned);

    if (summary) {
      for (const hsc::fsp::ground_lts& p : procs) {
        std::size_t trans = 0;
        for (const auto& [_, v] : p.rel) trans += v.size();
        std::cout << (p.is_property ? "property " : "process  ") << p.name
                  << ": " << p.state_names.size() << " states, "
                  << p.alphabet.size() << " labels, " << trans
                  << " transitions, " << p.tau.size() << " tau\n";
      }
      std::cout << in << ": " << t.labels << " labels -> " << t.events
                << " events (" << t.dead_labels << " dead labels, "
                << t.stutters << " stutters dropped), mon error = "
                << t.monitor_error << '\n';
      return 0;
    }

    std::vector<std::string> prov{"generated by fsp2hsc from " + in};
    if (!s1.empty()) {
      std::ifstream sf(s1);
      if (!sf) {
        std::cerr << "cannot open " << s1 << '\n';
        return 2;
      }
      std::string line, tasks;
      std::getline(sf, line);  // first line: the subject's path, dropped
      while (std::getline(sf, line))
        if (!line.empty()) tasks += " " + line;
      if (!tasks.empty()) prov.push_back("CAC08 S1 decomposition:" + tasks);
    }
    t.header.insert(t.header.begin(), prov.begin(), prov.end());

    if (out.empty()) {
      hsc::fsp::print_model(std::cout, t);
    } else {
      std::ofstream o(out, std::ios::binary);
      if (!o) {
        std::cerr << "cannot write " << out << '\n';
        return 2;
      }
      hsc::fsp::print_model(o, t);
    }
    if (!driver.empty()) {
      std::ofstream o(driver, std::ios::binary);
      if (!o) {
        std::cerr << "cannot write " << driver << '\n';
        return 2;
      }
      hsc::fsp::print_driver(o, t, basename_of(out.empty() ? in : out));
    }
    return 0;
  } catch (const hsc::fsp::parse_error& e) {
    std::cerr << in << ": parse error: " << e.what() << '\n';
    return 1;
  } catch (const hsc::fsp::ground_error& e) {
    std::cerr << in << ": ground error: " << e.what() << '\n';
    return 3;
  } catch (const hsc::fsp::transform_error& e) {
    std::cerr << in << ": transform error: " << e.what() << '\n';
    return 3;
  }
}
