#!/usr/bin/env python3
"""Emit a Towers of Hanoi model in the `.hsc` surface.

Loops live here, in the generator; the reader stays dumb and total. One leaf
per ring holds the pole it sits on; ring 0 is smallest and is laid deepest, so
an event's support is a suffix of the frontier. A move of ring k from a to b
requires no smaller ring on a or b, expressed as the separable per-ring
constraints `(!= r_j a) (!= r_j b)`.

Usage: hanoi.py N [POLES] [--naive]
  N        number of rings
  POLES    number of poles (default 3; reachable count is POLES not used —
           for 3 poles every configuration is reachable, so 3^N)
  --naive  also emit a naive-iteration reach, as a differential oracle
"""
import sys
from typing import List


def hanoi(n: int, poles: int = 3, naive: bool = False) -> str:
    out: List[str] = []
    out.append(f"; Towers of Hanoi: {n} rings, {poles} poles.")
    out.append(f"; Generated by tools/hanoi.py {n} {poles}.")
    for k in range(n):
        out.append(f"(leaf r{k} 0 {poles})")
    spine = " ".join(f"r{k}" for k in range(n - 1, -1, -1))  # smallest deepest
    out.append(f"(shape (spine {spine}))")
    out.append("(init)")  # all rings on pole 0 (each domain's low end)
    for k in range(n):
        for a in range(poles):
            for b in range(poles):
                if a == b:
                    continue
                whens = [f"(== r{k} {a})"]
                for j in range(k):  # no smaller ring on a or b
                    whens.append(f"(!= r{j} {a})")
                    whens.append(f"(!= r{j} {b})")
                out.append(
                    f"(event m{k}_{a}_{b} "
                    f"(when {' '.join(whens)}) (do (:= r{k} {b})))"
                )
    total = poles ** n if poles == 3 else None
    out.append("(reach R saturate)")
    out.append("(count R)")
    out.append("(nodes R)")
    if total is not None:
        out.append(f"(expect R {total})")
    if naive:
        out.append("(reach Rn naive)")
        if total is not None:
            out.append(f"(expect Rn {total})")
    out.append("(bill)")
    return "\n".join(out) + "\n"


def main(argv: List[str]) -> int:
    args = [a for a in argv[1:] if not a.startswith("--")]
    naive = "--naive" in argv
    if not args:
        print(__doc__)
        return 2
    n = int(args[0])
    poles = int(args[1]) if len(args) > 1 else 3
    sys.stdout.write(hanoi(n, poles, naive))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
