name: OSX Build

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [OSX]

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v6
    - name: build and test
      run: bash build_hsc.sh

    - name: Deploy binaries to the HSC-OSX branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          branch: HSC-OSX
          folder: website/
          clean: true
          single-commit: true
